name: CI

on:
    push:
        branches:
            - main
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    cs-fix:
        name: Run code style check
        runs-on: "ubuntu-24.04"
        strategy:
            matrix:
                php:
                    - '8.3'
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP Action
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none
                  extensions: 'pdo_sqlite, gd'
                  tools: cs2pr

            - uses: ramsey/composer-install@v3
              with:
                  dependency-versions: highest

            - name: Run code style check
              run: composer run-script check-cs -- --format=checkstyle | cs2pr

    rector:
        name: Run rector
        runs-on: "ubuntu-22.04"
        strategy:
            matrix:
                php:
                    - '8.3'
        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP Action
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
                    extensions: 'pdo_sqlite, gd'
                    tools: cs2pr

            -   uses: ramsey/composer-install@v3
                with:
                    dependency-versions: highest

            -   name: Run rector
                run: vendor/bin/rector process --dry-run --ansi

    tests:
        name: Unit tests
        runs-on: "ubuntu-24.04"
        timeout-minutes: 15

        strategy:
            fail-fast: false
            matrix:
                php:
                    - '8.3'

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP Action
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none
                  extensions: pdo_sqlite, gd
                  tools: cs2pr

            - uses: ramsey/composer-install@v3
              with:
                  dependency-versions: highest

            - name: Setup problem matchers for PHPUnit
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Run unit test suite
              run: composer test

            - name: Run PHPStan analysis
              run: composer run-script phpstan
